### ISSUE TITLE
java.lang.IllegalStateException: failed to get surface

### ISSUE THREAD

**Issue by ritesh-karmare** [HBiSoft/HBRecorder#1]
**This happens when I set the outputPath =  `getFilesDir() + "/demoVideos"`**

`java.lang.RuntimeException: Unable to start service com.hbisoft.hbrecorder.ScreenRecordService@72a1038 with Intent { cmp=com.app.guarddoor/com.hbisoft.hbrecorder.ScreenRecordService (has extras) }: java.lang.IllegalStateException: failed to get surface
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3713)
        at android.app.ActivityThread.access$1600(ActivityThread.java:202)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:198)
        at android.app.ActivityThread.main(ActivityThread.java:6729)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.IllegalStateException: failed to get surface
        at android.media.MediaRecorder.getSurface(Native Method)
        at com.hbisoft.hbrecorder.ScreenRecordService.createVirtualDisplay(ScreenRecordService.java:224)
        at com.hbisoft.hbrecorder.ScreenRecordService.onStartCommand(ScreenRecordService.java:146)
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3694)
        at android.app.ActivityThread.access$1600(ActivityThread.java:202) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:198) 
        at android.app.ActivityThread.main(ActivityThread.java:6729) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) `

**Comment by HBiSoft** [comment]
Did you create the folder before passing it too `HBRecorder`?

I tested with the demo app, if the folder is not created before passing the path, it will cause this.

First create the folder, by doing the following:

    String dirPath = getFilesDir() + File.separator + "demoVideos";
    File mFolder = new File(dirPath);
    if (!mFolder.exists()){
        mFolder.mkdirs();
    }

Then passing the following to `HBRecorder`

    hbRecorder.setOutputPath(getFilesDir() + File.separator + "demoVideos");

---

Currently you are passing a folder that doesn't exist.

**Comment by ritesh-karmare** [comment]
@HBiSoft  Thanks that WORKED!
