### ISSUE TITLE
Notification icon causes crash

### ISSUE THREAD

**Issue by JJdeGroot** [HBiSoft/HBRecorder#100]
**Describe the bug**
When starting the screen recorder, it immediately crashes when loading the default notification icon.

Somehow the Demo app does work. The only difference I can find is that it sets the notification icon with a byte array. When I do this, my own app still crashes. Other than changing the notification settings, everything is set to default.

**Log**
```
android.app.RemoteServiceException: Bad notification posted from package nl.ontoegankelijk: Couldn't create icon: StatusBarIcon(icon=Icon(typ=RESOURCE pkg=nl.ontoegankelijk id=0x7f0f0000) visible user=0 )
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1517)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5443)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
```

**Can it be reproduced in demo app**
No, it works in the demo app. The demo app does not show a notification. It does show the casting icon.

**HBRecorder version**
2.0.2

**Device information**
- Motorola XT1092
- Android 6.0 / API 23

**Screenshots**
Not applicable

**Comment by JJdeGroot** [comment]
The app also crashes on Lenovo P2a42 with Android 7 / API 24

```
android.app.RemoteServiceException: Bad notification posted from package nl.ontoegankelijk: Couldn't create icon: StatusBarIcon(icon=Icon(typ=RESOURCE pkg=nl.ontoegankelijk id=0x7f0f0000) visible user=0 )
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1637)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6111)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
```

**Comment by HBiSoft** [comment]
Please show me how you set the notification icon.

**Comment by JJdeGroot** [comment]
Setup:

```
        recorder = HBRecorder(this, this)
        recorder?.setNotificationTitle(getString(R.string.recording_notification_title))
        recorder?.setNotificationDescription(getString(R.string.recording_notification_message))
        recorder?.setNotificationButtonText(getString(R.string.recording_notification_action))
        recorder?.setNotificationSmallIcon(R.drawable.icon_notification)
```

**Comment by HBiSoft** [comment]
Ok, closing. I will reply on your other issue.
