### ISSUE TITLE
Crash when setting notification icon with alpha channel / vector

### ISSUE THREAD

**Issue by JJdeGroot** [HBiSoft/HBRecorder#101]
**Describe the bug**
App crashes when setting a notification icon resource which has an alpha channel and/or is a vector resource.

It crashes on this line `icon.compress(Bitmap.CompressFormat.PNG, 100, stream);` inside the `setNotificationSmallIcon` method.

icon_notification.xml
```
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="200dp"
    android:height="200dp"
    android:viewportWidth="850"
    android:viewportHeight="850">
  <path
      android:pathData="M600.667,0L850,249.333L850,600.667L600.667,850L249.333,850L0,600.667L0,249.333L249.333,0L600.667,0ZM675.541,276.625C669.621,257.324 649.388,246.185 629.871,251.602L629.871,251.602L462.688,298.222L461.831,298.493C437.526,306.101 411.457,306.011 387.194,298.222L387.194,298.222L219.874,251.602L219.288,251.445C199.953,246.409 180.065,257.517 174.204,276.625L174.204,276.625L174.029,277.212L173.887,277.738C171.452,287.038 172.751,296.931 177.519,305.294C182.377,313.815 190.434,320.044 199.902,322.596L199.902,322.596L352.33,364.615L352.723,364.724C364.605,368.1 372.853,378.934 372.919,391.324L372.919,391.324L372.919,441.513L372.916,442.645C372.767,466.775 367.236,490.573 356.723,512.301L356.723,512.301L274.847,681.614L274.614,682.106C270.569,690.811 270.104,700.767 273.332,709.822C276.562,718.884 283.227,726.302 291.874,730.481L291.874,730.481L292.347,730.706L292.904,730.965C311.291,739.364 333.085,731.583 341.967,713.335L341.967,713.335L424.872,542.374L508.052,713.335L508.323,713.879C517.369,731.737 538.912,739.28 557.116,730.965L557.116,730.965L557.672,730.706L558.145,730.481C566.792,726.302 573.457,718.884 576.687,709.822C579.977,700.596 579.431,690.435 575.173,681.614L575.173,681.614L493.503,512.301L493.013,511.281C482.655,489.488 477.287,465.653 477.306,441.513L477.306,441.513L477.306,391.324L477.309,390.916C477.493,378.695 485.643,368.004 497.414,364.615L497.414,364.615L649.842,322.596L650.348,322.455C659.597,319.82 667.455,313.663 672.226,305.294C676.994,296.931 678.292,287.038 675.858,277.738L675.858,277.738L675.716,277.212ZM424.872,97.325C386.476,97.325 355.35,128.464 355.35,166.877C355.35,205.289 386.476,236.428 424.872,236.428C463.268,236.428 494.395,205.289 494.395,166.877C494.395,128.464 463.268,97.325 424.872,97.325Z"
      android:strokeWidth="1"
      android:fillColor="#d023be"
      android:fillType="nonZero"
      android:strokeColor="#00000000"/>
</vector>
```

**Log**
```
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.graphics.Bitmap.compress(android.graphics.Bitmap$CompressFormat, int, java.io.OutputStream)' on a null object reference
        at com.hbisoft.hbrecorder.HBRecorder.setNotificationSmallIcon(HBRecorder.java:267)
        at nl.ontoegankelijk.ui.reporting.ScreenRecordingActivity.onViewCreated(ScreenRecordingActivity.kt:69)
        at nl.ontoegankelijk.ui.widgets.BaseActivity.onCreate(BaseActivity.kt:43)
        at android.app.Activity.performCreate(Activity.java:8000)
        at android.app.Activity.performCreate(Activity.java:7984)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1310)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3437)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3616) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2070) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.app.ActivityThread.main(ActivityThread.java:7711) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:952) 
```

**Can it be reproduced in demo app**
No, demo app uses byte array to set icon

**HBRecorder version**
2.0.2

**Device information**
- HMD Global Nokia 1.3
- Android 11

**Screenshots**
Not applicable

**Comment by JJdeGroot** [comment]
Setup code:
```
        recorder = HBRecorder(this, this)
        recorder?.setNotificationTitle(getString(R.string.recording_notification_title))
        recorder?.setNotificationDescription(getString(R.string.recording_notification_message))
        recorder?.setNotificationButtonText(getString(R.string.recording_notification_action))
        recorder?.setNotificationSmallIcon(R.drawable.icon_notification)
```

**Comment by HBiSoft** [comment]
Currently, vectors are not supported. I will add an option to set vectors tomorrow.

**Comment by HBiSoft** [comment]
Apologies for the delay. The [new release](https://github.com/HBiSoft/HBRecorder/releases/tag/2.0.3) `2.0.3` is now available. You are now able to use a vector drawable.
