### ISSUE TITLE
null point exeception on Vivo Android 10

### ISSUE THREAD

**Issue by h4h4da2** [HBiSoft/HBRecorder#103]
**Describe the bug**
crashed when start record screen

**Log**
    Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Intent.getAction()' on a null object reference
	at com.hbisoft.hbrecorder.ScreenRecordService.onStartCommand(ScreenRecordService.java:91)
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4408)

**Device**
 Vivo ,android 10

**HBRecorder version**
2.0.3

**Comment by h4h4da2** [comment]
maybe 

>  onStartCommand(final Intent intent, int flags, int startId)  return  START_REDELIVER_INTENT ; 

can slove this problem。or just return when intent is null
