### ISSUE TITLE
Some settings are not supported by your device. 

### ISSUE THREAD

**Issue by shahnavazansaribit** [HBiSoft/HBRecorder#104]
**Describe the bug**
"Some settings are not supported by your device."
    I've tried all the video encoders. For `HEVC` and `VP8` I am seeing a different error with error code `100`. But for the rest of the encoders this is the issue. I've tried changing output formats as well. None of them seems to work. I've observed that this issue I am facing is on the devices that have `MediaTek Processor`. Other devices seem to work

**Log**
```
2021-12-20 11:01:36.422 14847-14847/com.fnoplay E/EXAMPLE: THIS IS AN EXAMPLE OF HOW TO USE THE (HBRecorderCodecInfo) TO GET CODEC INFO:
2021-12-20 11:01:36.422 14847-14847/com.fnoplay E/HBRecorderCodecInfo: defaultVideoEncoder for (video/avc) -> OMX.MTK.VIDEO.ENCODER.AVC
2021-12-20 11:01:36.423 14847-14847/com.fnoplay W/System.err: java.lang.IllegalArgumentException: unsupported size
2021-12-20 11:01:36.423 14847-14847/com.fnoplay W/System.err:     at android.media.MediaCodecInfo$VideoCapabilities.getSupportedFrameRatesFor(MediaCodecInfo.java:1565)
2021-12-20 11:01:36.423 14847-14847/com.fnoplay W/System.err:     at com.marketwolf.screenrecorder.MWRecorder.MWRecorderCodecInfo.getMaxSupportedFrameRate(MWRecorderCodecInfo.java:302)
2021-12-20 11:01:36.423 14847-14847/com.fnoplay W/System.err:     at com.marketwolf.screenrecorder.MWRecorder.ScreenRecordService.initRecorder(ScreenRecordService.java:443)
2021-12-20 11:01:36.423 14847-14847/com.fnoplay W/System.err:     at com.marketwolf.screenrecorder.MWRecorder.ScreenRecordService.onStartCommand(ScreenRecordService.java:187)
2021-12-20 11:01:36.423 14847-14847/com.fnoplay W/System.err:     at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4373)
2021-12-20 11:01:36.423 14847-14847/com.fnoplay W/System.err:     at android.app.ActivityThread.access$2000(ActivityThread.java:244)
2021-12-20 11:01:36.423 14847-14847/com.fnoplay W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2001)
2021-12-20 11:01:36.423 14847-14847/com.fnoplay W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:106)
2021-12-20 11:01:36.423 14847-14847/com.fnoplay W/System.err:     at android.os.Looper.loop(Looper.java:223)
2021-12-20 11:01:36.423 14847-14847/com.fnoplay W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:7723)
2021-12-20 11:01:36.423 14847-14847/com.fnoplay W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2021-12-20 11:01:36.423 14847-14847/com.fnoplay W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:612)
2021-12-20 11:01:36.423 14847-14847/com.fnoplay W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:997)
2021-12-20 11:01:36.423 14847-14847/com.fnoplay E/HBRecorderCodecInfo: MaxSupportedFrameRate -> 0.0
2021-12-20 11:01:36.424 14847-14847/com.fnoplay E/HBRecorderCodecInfo: MaxSupportedBitrate -> 2000000
2021-12-20 11:01:36.424 14847-14847/com.fnoplay E/HBRecorderCodecInfo: isSizeAndFramerateSupported @ Width = 2400 Height = 1080 FPS = 30 -> false
2021-12-20 11:01:36.424 14847-14847/com.fnoplay E/HBRecorderCodecInfo: isSizeSupported @ Width = 2400 Height = 1080 -> false
2021-12-20 11:01:36.425 14847-14847/com.fnoplay E/HBRecorderCodecInfo: Default Video Format = WEBM
2021-12-20 11:01:36.425 14847-14847/com.fnoplay E/HBRecorderCodecInfo: Supported VIDEO encoders and mime types : c2.android.avc.encoder -> video/avc
2021-12-20 11:01:36.425 14847-14847/com.fnoplay E/HBRecorderCodecInfo: Supported VIDEO encoders and mime types : OMX.google.mpeg4.encoder -> video/mp4v-es
2021-12-20 11:01:36.425 14847-14847/com.fnoplay E/HBRecorderCodecInfo: Supported VIDEO encoders and mime types : OMX.MTK.VIDEO.ENCODER.H263 -> video/3gpp
2021-12-20 11:01:36.425 14847-14847/com.fnoplay E/HBRecorderCodecInfo: Supported VIDEO encoders and mime types : OMX.MTK.VIDEO.ENCODER.MPEG4 -> video/mp4v-es
2021-12-20 11:01:36.425 14847-14847/com.fnoplay E/HBRecorderCodecInfo: Supported VIDEO encoders and mime types : OMX.google.h264.encoder -> video/avc
2021-12-20 11:01:36.425 14847-14847/com.fnoplay E/HBRecorderCodecInfo: Supported VIDEO encoders and mime types : c2.android.vp8.encoder -> video/x-vnd.on2.vp8
2021-12-20 11:01:36.425 14847-14847/com.fnoplay E/HBRecorderCodecInfo: Supported VIDEO encoders and mime types : OMX.google.vp8.encoder -> video/x-vnd.on2.vp8
2021-12-20 11:01:36.425 14847-14847/com.fnoplay E/HBRecorderCodecInfo: Supported VIDEO encoders and mime types : OMX.MTK.VIDEO.ENCODER.AVC -> video/avc
2021-12-20 11:01:36.425 14847-14847/com.fnoplay E/HBRecorderCodecInfo: Supported VIDEO encoders and mime types : OMX.google.h263.encoder -> video/3gpp
2021-12-20 11:01:36.426 14847-14847/com.fnoplay E/HBRecorderCodecInfo: Supported VIDEO encoders and mime types : c2.android.mpeg4.encoder -> video/mp4v-es
2021-12-20 11:01:36.426 14847-14847/com.fnoplay E/HBRecorderCodecInfo: Supported VIDEO encoders and mime types : c2.android.h263.encoder -> video/3gpp
2021-12-20 11:01:36.426 14847-14847/com.fnoplay E/HBRecorderCodecInfo: Supported AUDIO encoders and mime types : c2.android.opus.encoder -> audio/opus
2021-12-20 11:01:36.426 14847-14847/com.fnoplay E/HBRecorderCodecInfo: Supported AUDIO encoders and mime types : c2.android.amrnb.encoder -> audio/3gpp
2021-12-20 11:01:36.426 14847-14847/com.fnoplay E/HBRecorderCodecInfo: Supported AUDIO encoders and mime types : c2.android.flac.encoder -> audio/flac
2021-12-20 11:01:36.426 14847-14847/com.fnoplay E/HBRecorderCodecInfo: Supported AUDIO encoders and mime types : OMX.google.amrnb.encoder -> audio/3gpp
2021-12-20 11:01:36.426 14847-14847/com.fnoplay E/HBRecorderCodecInfo: Supported AUDIO encoders and mime types : OMX.google.amrwb.encoder -> audio/amr-wb
2021-12-20 11:01:36.426 14847-14847/com.fnoplay E/HBRecorderCodecInfo: Supported AUDIO encoders and mime types : c2.android.aac.encoder -> audio/mp4a-latm
2021-12-20 11:01:36.426 14847-14847/com.fnoplay E/HBRecorderCodecInfo: Supported AUDIO encoders and mime types : OMX.google.aac.encoder -> audio/mp4a-latm
2021-12-20 11:01:36.426 14847-14847/com.fnoplay E/HBRecorderCodecInfo: Supported AUDIO encoders and mime types : c2.android.amrwb.encoder -> audio/amr-wb
2021-12-20 11:01:36.426 14847-14847/com.fnoplay E/HBRecorderCodecInfo: Supported AUDIO encoders and mime types : OMX.google.flac.encoder -> audio/flac
2021-12-20 11:01:36.428 14847-14847/com.fnoplay E/HBRecorderCodecInfo: Available Video Formats : MPEG_2_TS
2021-12-20 11:01:36.428 14847-14847/com.fnoplay E/HBRecorderCodecInfo: Available Video Formats : MPEG_4
2021-12-20 11:01:36.428 14847-14847/com.fnoplay E/HBRecorderCodecInfo: Available Video Formats : THREE_GPP
2021-12-20 11:01:36.428 14847-14847/com.fnoplay E/HBRecorderCodecInfo: Available Video Formats : WEBM
2021-12-20 11:01:36.428 14847-14847/com.fnoplay E/Available Encoders: OMX.MTK.VIDEO.ENCODER.AVC
2021-12-20 11:01:36.428 14847-14847/com.fnoplay E/Available Encoders: OMX.MTK.VIDEO.ENCODER.H263
2021-12-20 11:01:36.428 14847-14847/com.fnoplay E/Available Encoders: OMX.MTK.VIDEO.ENCODER.MPEG4
2021-12-20 11:01:36.428 14847-14847/com.fnoplay E/Available Encoders: c2.android.avc.encoder
2021-12-20 11:01:36.428 14847-14847/com.fnoplay E/Available Encoders: OMX.google.h264.encoder
2021-12-20 11:01:36.428 14847-14847/com.fnoplay E/Available Encoders: c2.android.h263.encoder
2021-12-20 11:01:36.428 14847-14847/com.fnoplay E/Available Encoders: OMX.google.h263.encoder
2021-12-20 11:01:36.428 14847-14847/com.fnoplay E/Available Encoders: c2.android.mpeg4.encoder
2021-12-20 11:01:36.428 14847-14847/com.fnoplay E/Available Encoders: OMX.google.mpeg4.encoder
2021-12-20 11:01:36.428 14847-14847/com.fnoplay E/Available Encoders: c2.android.vp8.encoder
2021-12-20 11:01:36.428 14847-14847/com.fnoplay E/Available Encoders: OMX.google.vp8.encoder
```

**Can it be reproduced in demo app**
Yes (screenshot attached)

**HBRecorder version**
2.0.1

**Device information**
- Redmi Note 8 Pro

**Screenshots**
![image](https://user-images.githubusercontent.com/36149330/146717636-b5eb17b0-2214-4f30-92e5-ba01a54d7465.png)
![image](https://user-images.githubusercontent.com/36149330/146717768-d4a1c3e4-9398-4a96-9b86-a3f205b63b9e.png)

**Comment by HBiSoft** [comment]
Can you try and change the resolution in the demo application to `1920x1080` and see if it works?

**Comment by shahnavazansaribit** [comment]
I tried the combination of H264 with Output format MPEG_4 with resolution 1920x1080. This works. But on my this device the resolution is 2400x1080. That is where I see this error.

**Comment by mhashim6** [comment]
Same on pixel 2 xl emulator API 28 and 29. No combination works

**Comment by Zatoner** [comment]
Found a working combination for api 28 but impossible to find one on api 29... impossible to record on api 29
