### ISSUE TITLE
Recording is failing on some devices.

### ISSUE THREAD

**Issue by mishu311289** [HBiSoft/HBRecorder#109]
READ THIS BEFORE OPENING AN ISSUE:
-----------------------
- Fill in all the information below.
- Have a look at previously asked questions to see if your issue has been resolved.
- Properly format your issue.
- All issues should be asked in English.
- Delete all the above before posting your issue

**Describe the bug**
Recording is failing on some devices like Motorola Moto X play (Android 7.1.1), Motorola Droid Maxx 2 (Android 7.1.1) and some other devices

**Log**
    02-24 13:59:49.156 11182 11182 E HBRecorderOnError: java.io.IOException: prepare failed.
    02-24 13:59:49.156 11182 11182 E HBRecorderOnError: 	at android.media.MediaRecorder._prepare(Native Method)
    02-24 13:59:49.156 11182 11182 E HBRecorderOnError: 	at android.media.MediaRecorder.prepare(MediaRecorder.java:848)
    02-24 13:59:49.156 11182 11182 E HBRecorderOnError: 	at 
    com.hbisoft.hbrecorder.ScreenRecordService.initRecorder(ScreenRecordService.java:529)
    02-24 13:59:49.156 11182 11182 E HBRecorderOnError: 	at 
    com.hbisoft.hbrecorder.ScreenRecordService.onStartCommand(ScreenRecordService.java:235)
    02-24 13:59:49.156 11182 11182 E HBRecorderOnError: 	at 
    android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3347)
    02-24 13:59:49.156 11182 11182 E HBRecorderOnError: 	at android.app.ActivityThread.-wrap21(ActivityThread.java)
    02-24 13:59:49.156 11182 11182 E HBRecorderOnError: 	at 
    android.app.ActivityThread$H.handleMessage(ActivityThread.java:1595)
    02-24 13:59:49.156 11182 11182 E HBRecorderOnError: 	at android.os.Handler.dispatchMessage(Handler.java:102)
    02-24 13:59:49.156 11182 11182 E HBRecorderOnError: 	at android.os.Looper.loop(Looper.java:154)
    02-24 13:59:49.156 11182 11182 E HBRecorderOnError: 	at android.app.ActivityThread.main(ActivityThread.java:6165)
    02-24 13:59:49.156 11182 11182 E HBRecorderOnError: 	at java.lang.reflect.Method.invoke(Native Method)
    02-24 13:59:49.156 11182 11182 E HBRecorderOnError: 	at 
    com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
    02-24 13:59:49.156 11182 11182 E HBRecorderOnError: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:778)
    02-24 13:59:49.165 11182 11182 E HBRecorderOnError: java.lang.IllegalStateException: failed to get surface
    02-24 13:59:49.165 11182 11182 E HBRecorderOnError: 	at android.media.MediaRecorder.getSurface(Native Method)
    02-24 13:59:49.165 11182 11182 E HBRecorderOnError: 	at 
    com.hbisoft.hbrecorder.ScreenRecordService.initVirtualDisplay(ScreenRecordService.java:535)
    02-24 13:59:49.165 11182 11182 E HBRecorderOnError: 	at 
    com.hbisoft.hbrecorder.ScreenRecordService.onStartCommand(ScreenRecordService.java:259)
    02-24 13:59:49.165 11182 11182 E HBRecorderOnError: 	at 
    android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3347)
    02-24 13:59:49.165 11182 11182 E HBRecorderOnError: 	at android.app.ActivityThread.-wrap21(ActivityThread.java)
    02-24 13:59:49.165 11182 11182 E HBRecorderOnError: 	at 
    android.app.ActivityThread$H.handleMessage(ActivityThread.java:1595)
    02-24 13:59:49.165 11182 11182 E HBRecorderOnError: 	at android.os.Handler.dispatchMessage(Handler.java:102)
    02-24 13:59:49.165 11182 11182 E HBRecorderOnError: 	at android.os.Looper.loop(Looper.java:154)
    02-24 13:59:49.165 11182 11182 E HBRecorderOnError: 	at android.app.ActivityThread.main(ActivityThread.java:6165)
    02-24 13:59:49.165 11182 11182 E HBRecorderOnError: 	at java.lang.reflect.Method.invoke(Native Method)
    02-24 13:59:49.165 11182 11182 E HBRecorderOnError: 	at 
    com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
    02-24 13:59:49.165 11182 11182 E HBRecorderOnError: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:778)

**Can it be reproduced in demo app**
Yes

**HBRecorder version**
the latest one available on git. Sample app says version 1.0

**Device information**
- Motorola Moto X play
- Android 7.1.1

**Screenshots**

**Comment by mishu311289** [comment]
Can anybody help regarding that?
