### ISSUE TITLE
illegalStateException with errorCode 268435556 in Android 8

### ISSUE THREAD

**Issue by ANHNST** [HBiSoft/HBRecorder#110]
**Describe the bug**
When I record a video call (using react-native-webRTC library to handle) in device Sony XZ2 Android 8 and get error java.lang.IllegalStateException with errorCode 268435556
but when I record in device XiaoMi BlackShark 3 Android 11 then HBRecorder record normal.
**Log**
Please provide a well formatted bug report (by adding 4 spaces before the log)

    2022-03-03 16:37:44.968 19208-19208/com.gmo.rio E/HBRecorderOnError: java.lang.IllegalStateException
        at android.media.MediaRecorder.start(Native Method)
        at com.hbisoft.hbrecorder.ScreenRecordService.onStartCommand(ScreenRecordService.java:305)
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3576)
        at android.app.ActivityThread.-wrap20(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1704)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:251)
        at android.app.ActivityThread.main(ActivityThread.java:6599)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
    2022-03-03 16:37:44.969 19208-19208/com.gmo.rio E/HBRecorderOnError: 268435556

**Can it be reproduced in demo app**
NO

**HBRecorder version**
2.0.3

**Device information**
- Make/model: Sony XZ2 - Sony H8216
- SDK version: Android 8 API 26

**Screenshots**
![image](https://user-images.githubusercontent.com/90667991/156539696-477f5031-f0a0-4fb3-bb76-be53c0c0da9b.png)

**Comment by HBiSoft** [comment]
This issue slipped by me somehow. It's pointing to `MediaRecorder.MEDIA_RECORDER_INFO_MAX_FILESIZE_REACHED`. I assume you set a max file size.
