### ISSUE TITLE
Crash from Crashlytics

### ISSUE THREAD

**Issue by robertlevonyan** [HBiSoft/HBRecorder#112]
**Describe the bug**
The crash is from crashlytics

**Log**
```
Fatal Exception: java.lang.RuntimeException: Unable to start service com.hbisoft.hbrecorder.ScreenRecordService@9f77c30 with null: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Intent.getAction()' on a null object reference
       at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4786)
       at android.app.ActivityThread.access$1900(ActivityThread.java:301)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2188)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:246)
       at android.app.ActivityThread.main(ActivityThread.java:8587)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

```
**Can it be reproduced in demo app**
no

**HBRecorder version**
2.0.3

**Device information**
- Galaxy A20
- SDK version 30

**Comment by HBiSoft** [comment]
I cannot believe this issue was not reported before. I fixed it and will push the new release shortly.
My apologies for this simple mistake and thank you for reporting it.

**Comment by HBiSoft** [comment]
It should be fixed in `2.0.4`
