### ISSUE TITLE
App carsh when start the recording 

### ISSUE THREAD

**Issue by hitesharora1992** [HBiSoft/HBRecorder#113]
```
2022-04-14 19:04:33.858 9502-9502/com.my.screenrecorder E/MediaRecorder: SurfaceMediaSource could not be initialized!
2022-04-14 19:04:33.861 9502-9502/com.my.screenrecorder E/MediaRecorder: start called in an invalid state: 32
2022-04-14 19:04:33.902 9502-9502/com.my.screenrecorder E/ErrorHB: E Bundle[{errorReason=java.lang.RuntimeException: setAudioSource failed.
        at android.media.MediaRecorder._setAudioSource(Native Method)
        at android.media.MediaRecorder.setAudioSource(MediaRecorder.java:798)
        at com.hbisoft.hbrecorder.ScreenRecordService.initRecorder(ScreenRecordService.java:476)
        at com.hbisoft.hbrecorder.ScreenRecordService.onStartCommand(ScreenRecordService.java:236)
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4784)
        at android.app.ActivityThread.access$1900(ActivityThread.java:301)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2204)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:246)
        at android.app.ActivityThread.main(ActivityThread.java:8633)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
    }]
2022-04-14 19:04:33.902 9502-9502/com.my.screenrecorder E/ErrorHB: Check100
2022-04-14 19:04:33.957 9502-9502/com.my.screenrecorder E/ErrorHB: E Bundle[{errorReason=java.lang.IllegalStateException: failed to get surface
        at android.media.MediaRecorder.getSurface(Native Method)
        at com.hbisoft.hbrecorder.ScreenRecordService.initVirtualDisplay(ScreenRecordService.java:538)
        at com.hbisoft.hbrecorder.ScreenRecordService.onStartCommand(ScreenRecordService.java:260)
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4784)
        at android.app.ActivityThread.access$1900(ActivityThread.java:301)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2204)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:246)
        at android.app.ActivityThread.main(ActivityThread.java:8633)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
    }]
2022-04-14 19:04:33.957 9502-9502/com.my.screenrecorder E/ErrorHB: Check100
2022-04-14 19:04:33.976 9502-9502/com.my.screenrecorder E/ErrorHB: E Bundle[{errorReason=java.lang.IllegalStateException
        at android.media.MediaRecorder._start(Native Method)
        at android.media.MediaRecorder.start(MediaRecorder.java:1467)
        at com.hbisoft.hbrecorder.ScreenRecordService.onStartCommand(ScreenRecordService.java:306)
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4784)
        at android.app.ActivityThread.access$1900(ActivityThread.java:301)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2204)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:246)
        at android.app.ActivityThread.main(ActivityThread.java:8633)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
    , error=38}]
2022-04-14 19:04:33.976 9502-9502/com.my.screenrecorder E/ErrorHB: Check38
2022-04-14 19:04:34.010 9502-9502/com.my.screenrecorder E/ErrorHB: E Bundle[{onComplete=Uri was passed}]

```

**Comment by hitesharora1992** [comment]
its is working when i start the recording in the app. when app in background mode when i start the recording through floating button or notification bar then this error accorded.

**Comment by hitesharora1992** [comment]
i have set the audio source before starting the recording

**Comment by HBiSoft** [comment]
>its is working when i start the recording in the app. when app in background mode when i start the recording through floating button or notification bar then that error accorded.

Is there any other applications running when you start the recording?

>i have set the audio source before starting the recording

What did you set it to?

**Comment by hitesharora1992** [comment]
i have set Mic in audio source

**Comment by hitesharora1992** [comment]
no other application is running when i start the recording.

**Comment by HBiSoft** [comment]
With the small amount of information you have provided, it's impossible to help you.

Please provide the code snippet where you start the recording from your floating button (background) and where you start the recording from inside the application (foreground).

**Comment by hitesharora1992** [comment]
https://user-images.githubusercontent.com/103649570/163550772-eb157969-7fad-4abc-a1e1-74db85c867f8.mp4

**Comment by HBiSoft** [comment]
>Please provide the code snippet where you start the recording from your floating button (background) and where you start the recording from inside the application (foreground).

**Comment by HBiSoft** [comment]
@hitesharora1992 Did you resolve this issue? What was wrong?
