### ISSUE TITLE
HBrecoderonerror 38

### ISSUE THREAD

**Issue by meharunnisa414** [HBiSoft/HBRecorder#126]
**Describe the bug**
when we start recording it gets stuck at one point and dont stop video and dont pause it. and give error 38.

**Log**
2022-07-14 17:47:20.139 20798-20825/? E/ActivityThread: Failed to find provider info for com.samsung.cmh
2022-07-14 17:47:20.140 20798-20825/? E/SecMediaProvider: failed to notify cmh
    java.lang.IllegalArgumentException: Unknown authority com.samsung.cmh
        at android.content.ContentResolver.call(ContentResolver.java:2412)
        at android.content.ContentResolver.call(ContentResolver.java:2395)
        at com.samsung.android.providers.media.MediaProvider.lambda$static$2(MediaProvider.java:344)
        at com.samsung.android.providers.media.-$$Lambda$MediaProvider$nC3Gy5JVa0aXu9d6JvgA1hm--6k.accept(Unknown Source:4)
        at com.samsung.android.providers.media.DatabaseHelper.notifyChangeInternal(DatabaseHelper.java:415)
        at com.samsung.android.providers.media.DatabaseHelper.lambda$endTransactionInternal$0(DatabaseHelper.java:292)
        at com.samsung.android.providers.media.DatabaseHelper.lambda$endTransactionInternal$0$DatabaseHelper(Unknown Source:0)
        at com.samsung.android.providers.media.-$$Lambda$DatabaseHelper$Ri05MQOHBXWRuFN6N8X5K8EzbEE.run(Unknown Source:4)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:246)
        at android.os.HandlerThread.run(HandlerThread.java:67)

**HBRecorder version**
implementation 'com.github.HBiSoft:HBRecorder:1

**Device information**
- android version 10 and 11-
- infinix/oppo

**Comment by HBiSoft** [comment]
What version of the library are you using?
