### ISSUE TITLE
Caused by java.lang.NullPointerException

### ISSUE THREAD

**Issue by Sohaib-Raza** [HBiSoft/HBRecorder#127]
READ THIS BEFORE OPENING AN ISSUE:
-----------------------

**Describe the bug**
 Attempt to invoke virtual method 'long android.content.Intent.getLongExtra(java.lang.String, long)' on a null object reference

**Log**
        com.hbisoft.hbrecorder.ScreenRecordService.onStartCommand (ScreenRecordService.java:119)
        android.app.ActivityThread.handleServiceArgs (ActivityThread.java:4415)
        android.app.ActivityThread.access$1800 (ActivityThread.java:270)
        android.app.ActivityThread$H.handleMessage (ActivityThread.java:2083)
        android.os.Handler.dispatchMessage (Handler.java:107)
        android.os.Looper.loop (Looper.java:237)
        android.app.ActivityThread.main (ActivityThread.java:7948)
        java.lang.reflect.Method.invoke (Method.java)
        com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:493)
        com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1075)

**Can it be reproduced in demo app**
no

**HBRecorder version**
2.0.5

**Device information**
- Samsung (Galaxy A10, GA30s)
- Oppo

Android version 8.1.0, 9, 10, 11

**Screenshots**
![Capture](https://user-images.githubusercontent.com/14075651/180220900-05876671-4cc1-4e57-9e69-72b196053cfe.PNG)

**Comment by HBiSoft** [comment]
Are you setting a max file size (`HBRecorder.setMaxFileSize(long)`)?

**Comment by Sohaib-Raza** [comment]
No, I am not seting the HBRecorder.setMaxFileSize(long). Its necessary?

**Comment by ahmadbajwa0328** [comment]
Fatal Exception: java.lang.RuntimeException: Unable to start service com.hbisoft.hbrecorder.ScreenRecordService@2ad934d with null: java.lang.NullPointerException: Attempt to invoke virtual method 'long android.content.Intent.getLongExtra(java.lang.String, long)' on a null object reference
       at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4813)
       at android.app.ActivityThread.access$2000(ActivityThread.java:301)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2215)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:246)
       at android.app.ActivityThread.main(ActivityThread.java:8653)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'long android.content.Intent.getLongExtra(java.lang.String, long)' on a null object reference
       at com.hbisoft.hbrecorder.ScreenRecordService.onStartCommand(ScreenRecordService.java:4)
       at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4795)
       at android.app.ActivityThread.access$2000(ActivityThread.java:301)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2215)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:246)
       at android.app.ActivityThread.main(ActivityThread.java:8653)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

**Comment by Sohaib-Raza** [comment]
I am still getting this error after set HBRecorder.setMaxFileSize(long)
I am using version 2.0.5

![1](https://user-images.githubusercontent.com/14075651/183005371-a27bcf0c-0937-44a7-b487-0cf670be85b5.PNG)
,

**Comment by sofronovicnikola** [comment]
Please check #129
