### ISSUE TITLE
Notification Icon Error

### ISSUE THREAD

**Issue by igorsantos314** [HBiSoft/HBRecorder#170]
**Bug description**
I'm having problems starting screen recording on Android api 25. I verified that the problem is with the recording after debugging and removing the recording start code from hbrecorder, the app works perfectly, otherwise it's not possible to record, because an error occurs fatal

**Log**
```
android.app.RemoteServiceException: Bad notification posted from package [myapp]: Couldn't create icon: StatusBarIcon(icon=Icon(typ=RESOURCE pkg= [myapp] id=0x7f100002) visible user=0 )
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                                    	at android.os.Looper.loop(Looper.java:154)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

**Can it be reproduced in demo app**
no

**HBRecorder version**
I am using HBRecorder version 3.0.3

**Device information**
- Emulator Pixel 6, Galaxy Grand Prime Pro e Moto G4 Play
- SDK version 25 - Android 7.1

**Comment by HBiSoft** [comment]
This is most probably caused by the icon you are providing to HBRecorder. Sorry, but there is nothing I can help you with here. Ensure you are passing the drawable correctly and that it actually exists.

**Comment by igorsantos314** [comment]
In fact, this problem persists regardless of whether there is an icon or not.
