### ISSUE TITLE
SecurityException when Starting Foreground Service with Microphone Type

### ISSUE THREAD

**Issue by calambrenet** [HBiSoft/HBRecorder#173]
Using this library, the application encounters a SecurityException when attempting to start a foreground service with the microphone type. The error message indicates that the app requires specific permissions and must be in an eligible state to access the foreground-only permission.

`Caused by: java.lang.SecurityException: Starting FGS with type microphone callerApp=ProcessRecord{4b28b66 7326:com.example.screenrecord/u0a205} targetSDK=34 requires permissions: all of the permissions allOf=true [android.permission.FOREGROUND_SERVICE_MICROPHONE] any of the permissions allOf=false [android.permission.CAPTURE_AUDIO_HOTWORD, android.permission.CAPTURE_AUDIO_OUTPUT, android.permission.CAPTURE_MEDIA_OUTPUT, android.permission.CAPTURE_TUNER_AUDIO_INPUT, android.permission.CAPTURE_VOICE_COMMUNICATION_OUTPUT, android.permission.RECORD_AUDIO]  and the app must be in the eligible state/exemptions to access the foreground only permission
                                                                                                    	at android.os.Parcel.createExceptionOrNull(Parcel.java:3242)
                                                                                                    	at android.os.Parcel.createException(Parcel.java:3226)
                                                                                                    	at android.os.Parcel.readException(Parcel.java:3209)
                                                                                                    	at android.os.Parcel.readException(Parcel.java:3151)
                                                                                                    	at android.app.IActivityManager$Stub$Proxy.setServiceForeground(IActivityManager.java:7167)
                                                                                                    	at android.app.Service.startForeground(Service.java:863)
                                                                                                    	at com.hbisoft.hbrecorder.ScreenRecordService.startFgs(ScreenRecordService.java:619)
                                                                                                    	at com.hbisoft.hbrecorder.ScreenRecordService.onStartCommand(ScreenRecordService.java:239)
                                                                                                    	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:5146)`

This is my manifest:

`<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools">

    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.WRITE_INTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.RECORD_AUDIO" />
    <uses-permission android:name="android.permission.FOREGROUND_SERVICE" />
    <uses-permission android:name="android.permission.FOREGROUND_SERVICE_MICROPHONE" />
    <uses-permission android:name="android.permission.CAPTURE_AUDIO_OUTPUT" />
    <uses-permission android:name="android.permission.CAPTURE_AUDIO_HOTWORD" />
    <uses-permission android:name="android.permission.CAPTURE_MEDIA_OUTPUT" />
    <uses-permission android:name="android.permission.RECORD_AUDIO" />
    <uses-permission android:name="android.permission.CAPTURE_VOICE_COMMUNICATION_AUTPUT" />
    
    <uses-permission android:name="android.permission.FOREGROUND_SERVICE_MEDIA_PROJECTION" />

    <application...`

**Comment by HBiSoft** [comment]
Can you reproduce this in the demo app? What device are you using?

**Comment by calambrenet** [comment]
Ok. I needed to verify all permissions before I started recording.
Now it works correctly.
Thx!
