### ISSUE TITLE
Xiaomi 14 [Android]

### ISSUE THREAD

**Issue by ji4ozhu** [HBiSoft/HBRecorder#176]
Xiaomi 14
Android 14 
Android 14 - 6.1.57-android14-11-gb8b333a26dfd-ab11564698

**Log**
java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=777, result=-1, data=Intent { (has extras) }} to activity {com.hbisoft.hbrecorderexample/com.hbisoft.hbrecorderexample.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.hashCode()' on a null object reference
	at android.app.ActivityThread.deliverResults(ActivityThread.java:5809)
	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5853)
	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:70)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:99)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2601)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:224)
	at android.os.Looper.loop(Looper.java:318)
	at android.app.ActivityThread.main(ActivityThread.java:8759)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.hashCode()' on a null object reference
	at com.hbisoft.hbrecorderexample.MainActivity.getMimeTypeForOutputFormat(MainActivity.java:665)
	at com.hbisoft.hbrecorderexample.MainActivity.setOutputPath(MainActivity.java:650)
	at com.hbisoft.hbrecorderexample.MainActivity.onActivityResult(MainActivity.java:625)
	at android.app.Activity.dispatchActivityResult(Activity.java:9298)
	at android.app.ActivityThread.deliverResults(ActivityThread.java:5802)
	... 13 more

![20240905-223010](https://github.com/user-attachments/assets/79a5bee5-3dcc-46c1-8469-4ea623666da9)

**Comment by HBiSoft** [comment]
Fixed in [3.0.7](https://github.com/HBiSoft/HBRecorder/releases/tag/3.0.7)
