### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by huantca** [HBiSoft/HBRecorder#177]
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.media.projection.MediaProjection.registerCallback(android.media.projection.MediaProjection$Callback, android.os.Handler)' on a null object reference (Ask Gemini)
                                                                                                    	at com.hbisoft.hbrecorder.ScreenRecordService.initMediaProjection(ScreenRecordService.java:498)
                                                                                                    	at com.hbisoft.hbrecorder.ScreenRecordService.onStartCommand(ScreenRecordService.java:266)
                                                                                                    	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:5053)
                                                                                                    	at android.app.ActivityThread.-$$Nest$mhandleServiceArgs(Unknown Source:0)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2435)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:224)
                                                                                                    	at android.os.Looper.loop(Looper.java:318)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8763)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)

**Comment by HBiSoft** [comment]
Please see [Always fill in the issue template](https://github.com/HBiSoft/HBRecorder/issues/31)
