### ISSUE TITLE
Throw error if start record in app background with Android 14

### ISSUE THREAD

**Issue by aduonggm** [HBiSoft/HBRecorder#181]
READ THIS BEFORE OPENING AN ISSUE:

**Describe the bug**
I did the permission request on android 14. but after 3 seconds it started recording the screen. during those 3 seconds I brought the phone back to the home screen and this error appeared

**Log**
 Caused by: java.lang.SecurityException: Starting FGS with type microphone callerApp=ProcessRecord{6ce5b8a 6736:com.hbisoft.hbrecorderexample/u0a321} targetSDK=34 requires permissions: all of the permissions allOf=true [android.permission.FOREGROUND_SERVICE_MICROPHONE] any of the permissions allOf=false [android.permission.CAPTURE_AUDIO_HOTWORD, android.permission.CAPTURE_AUDIO_OUTPUT, android.permission.CAPTURE_MEDIA_OUTPUT, android.permission.CAPTURE_TUNER_AUDIO_INPUT, android.permission.CAPTURE_VOICE_COMMUNICATION_OUTPUT, android.permission.RECORD_AUDIO]  and the app must be in the eligible state/exemptions to access the foreground only permission
                                                                	at android.os.Parcel.createExceptionOrNull(Parcel.java:3069)
                                                                	at android.os.Parcel.createException(Parcel.java:3053)
                                                                	at android.os.Parcel.readException(Parcel.java:3036)
                                                                	at android.os.Parcel.readException(Parcel.java:2978)
                                                                	at android.app.IActivityManager$Stub$Proxy.setServiceForeground(IActivityManager.java:7220)
                                                                	at android.app.Service.startForeground(Service.java:862)
                                                                	at com.hbisoft.hbrecorder.ScreenRecordService.startFgs(ScreenRecordService.java:619)
                                                                	at com.hbisoft.hbrecorder.ScreenRecordService.onStartCommand(ScreenRecordService.java:239)
                                                                	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:5268)
                                                                	at android.app.ActivityThread.-$$Nest$mhandleServiceArgs(Unknown Source:0) 
                                                                	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2531) 
                                                                	at android.os.Handler.dispatchMessage(Handler.java:106) 
                                                                	at android.os.Looper.loopOnce(Looper.java:230) 
                                                                	at android.os.Looper.loop(Looper.java:319) 
                                                                	at android.app.ActivityThread.main(ActivityThread.java:8918) 
                                                                	at java.lang.reflect.Method.invoke(Native Method) 
                                                                	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608) 
                                                                	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103) 
-----------------------

**Can it be reproduced in demo app**
Yes or no

**HBRecorder version**
for example 3.0.7

**Device information**
- Make/model Samsung S24 Utral
- SDK version 34

**Screenshots**

**Comment by AbdulWahab1539** [comment]
Does this happens on the Demo app provided in the repo? or you have have implemented custom timer mechanism of 3 seconds at your side?

**Comment by HBiSoft** [comment]
More context/information needed. 

Closing for now.
