### ISSUE TITLE
When zoom meeting is running if i start recording i am getting error

### ISSUE THREAD

**Issue by ramdisk-ott** [HBiSoft/HBRecorder#21]
**Describe the bug**
When zoom meeting is running if i start recording i am getting error
**Log**
2020-07-17 21:15:34.303 5997-5997/com.hbisoft.hbrecorderexample E/MediaRecorder: start failed: -38
2020-07-17 21:15:34.328 5997-5997/com.hbisoft.hbrecorderexample E/CALLED: CALLED
2020-07-17 21:15:34.369 5997-5997/com.hbisoft.hbrecorderexample E/HBRecorderOnError: java.lang.IllegalStateException
        at android.media.MediaRecorder.start(Native Method)
        at com.hbisoft.hbrecorder.ScreenRecordService.onStartCommand(ScreenRecordService.java:231)
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3668)
        at android.app.ActivityThread.access$1600(ActivityThread.java:200)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1682)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6692)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
2020-07-17 21:15:34.374 5997-5997/com.hbisoft.hbrecorderexample E/CALLED: CALLED
2020-07-17 21:15:34.384 5997-5997/com.hbisoft.hbrecorderexample E/HBRecorderOnError: 268435556

**Can it be reproduced in demo app**
Yes

**HBRecorder version**
for example 1.0

**Device information**
- Make/model ASUS
- SDK version 29

**Screenshots**

Thanks
Ramesh

**Comment by HBiSoft** [comment]
Please try and disable the audio recording and check if it works then.

**Comment by ramdisk-ott** [comment]
> Please try and disable the audio recording and check if it works then.

**Comment by ramdisk-ott** [comment]
its working if I disable the audio.but audio functionality required

**Comment by HBiSoft** [comment]
Can you please confirm if you are using Android 10?

This should be working if you are, according to the [docs](https://developer.android.com/guide/topics/media/sharing-audio-input#pre-behavior).

If you are using Android 10 then I will have to look at implementing an [AccessibilityServer](https://developer.android.com/reference/android/accessibilityservice/AccessibilityService) instead of an ordinary `ForgroundService`.

Before I do this, can you please set the audio source to the following and check if it works:

    hbRecorder.setAudioSource("VOICE_RECOGNITION");

**Comment by ramdisk-ott** [comment]
(https://user-images.githubusercontent.com/62267259/87849122-af382a80-c903-11ea-850e-82658ccb918f.jpeg)
I tried the below snippet  which u shared but its not working
**hbRecorder.setAudioSource("VOICE_RECOGNITION");**

I am using android 9 version(api 28). please find attached device info screenshot.

**Comment by HBiSoft** [comment]
This is to be expected. From the [docs](https://developer.android.com/guide/topics/media/sharing-audio-input#pre-behavior):

>Before Android 10 the input audio stream could only be captured by one app at a time. If some app was already recording or listening to audio, your app could create an AudioRecord object, but an error would be returned when you called AudioRecord.startRecording() and the recording would not start.

>One exception to this rule was when a privileged app (like Google Assistant or an accessibility service) had the permission android.permission.CAPTURE_AUDIO_HOTWORD and used an audio source of type HOTWORD. In this case another app could start recording. When that happened the privileged app terminated and the new app captured the input.

You can't record audio from more than one source on devices running 28 and lower.

There was another question regarding this(#14)
I'm sorry but I will have to close this issue since there is nothing I can do about this.

**Comment by ramdisk-ott** [comment]
both(recording and zoom meeting) are running in same app.
if I start the recording first and starts the zoom meeting its working fine.
if I start the zoom meeting first and then start the recording its not working.

**Comment by HBiSoft** [comment]
`both(recording and zoom meeting) are running in same app.`
What do you mean? Did you implement the zoom sdk into your application?

`if I start the recording first and starts the zoom meeting its working fine.`
Yes, this will work because the app in progress is prioritized. In this case your application is started first, so you have access to audio. When doing this, your zoom audio will not work.
