### ISSUE TITLE
HBRecorderOnError:: errorCode: 100 reason: java.lang.IllegalStateException

### ISSUE THREAD

**Issue by aruproy** [HBiSoft/HBRecorder#45]
Got HBRecorderOnError callback on first call to HBRecorder startScreenRecording on one device. This is a production issue and I don't know if any other recorder was active at that time (also don't know if that matters). Not sure if this a HBRecorder bug or, this needs to handled for retry. I'd appreciate any help.

**Describe the bug**
Got this error `HBRecorderOnError:: errorCode: 100 reason: java.lang.IllegalStateException` on first `hbRecorder.startScreenRecording` call after install.

**Log**
```
HBRecorderOnError:: errorCode: 100 reason: java.lang.IllegalStateException
        at android.media.MediaRecorder.start(Native Method)
        at com.hbisoft.hbrecorder.ScreenRecordService.onStartCommand(SourceFile:83)
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3672)
        at android.app.ActivityThread.-wrap21(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1825)
        at android.os.Handler.dispatchMessage(Handler.java:110)
        at android.os.Looper.loop(Looper.java:232)
        at android.app.ActivityThread.main(ActivityThread.java:6806)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1103)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
```

**Can it be reproduced in demo app**
This is a production issue - no access to the physical device.

**HBRecorder version**
HBRecorder:0.1.14

**Device information**
OPPO CPH1729
SDK version 25

**Comment by HBiSoft** [comment]
Have a look at what I've commented here:

https://github.com/HBiSoft/HBRecorder/blob/9c36cec89ff2fd3ef7e07e9a4065bb8d0b233a40/hbrecorder/src/main/java/com/hbisoft/hbrecorder/ScreenRecordService.java#L268

I will improve the logging tomorrow to provide more detailed logs.

**Comment by aruproy** [comment]
@HBiSoft Thank you so much for your quick response.

**Comment by HBiSoft** [comment]
@aruproy 
Just an update on this. I will be updating the library in the next few days. In the meantime, you can let the user know that they must ensure that there is no camera/media player using the microphone running in the background.

I will be closing the issue for now and let you know when I've updated the library.
