### ISSUE TITLE
Crashing on stop

### ISSUE THREAD

**Issue by robertlevonyan** [HBiSoft/HBRecorder#50]
The app is crashing from your library.

```
Fatal Exception: java.lang.RuntimeException: Unable to stop service com.hbisoft.hbrecorder.ScreenRecordService@bf32d6: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.media.projection.MediaProjection.stop()' on a null object reference
       at android.app.ActivityThread.handleStopService(ActivityThread.java:4137)
       at android.app.ActivityThread.access$1900(ActivityThread.java:220)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1897)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7397)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)
```

**Comment by HBiSoft** [comment]
Please see [Always fill in the issue template](https://github.com/HBiSoft/HBRecorder/issues/31)
