### ISSUE TITLE
The app is crashing with this exception.

### ISSUE THREAD

**Issue by robertlevonyan** [HBiSoft/HBRecorder#60]
**Describe the bug**
The crash is on Crashlytics

**Log**
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'android.os.Parcelable android.content.Intent.getParcelableExtra(java.lang.String)' on a null object reference
       at com.hbisoft.hbrecorder.ScreenRecordService.callOnComplete(ScreenRecordService.java:4)
       at com.hbisoft.hbrecorder.ScreenRecordService.onDestroy(ScreenRecordService.java:6)
       at android.app.ActivityThread.handleStopService(ActivityThread.java:4117)
       at android.app.ActivityThread.access$1900(ActivityThread.java:220)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1897)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7403)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)

**Can it be reproduced in demo app**
No

**HBRecorder version**
0.1.15

**Device information**
- Xiaomi Mi A2
- SDK version: 30

**Comment by HBiSoft** [comment]
Thanks for reporting this. I will add a try/catch to check if the `Intent` is `null`. I will update the library in the next hour or so.

**Comment by robertlevonyan** [comment]
Thank you

**Comment by robertlevonyan** [comment]
any news about update?

**Comment by robertlevonyan** [comment]
Does it mean that in the new version there will be fix for the issue, or it will be just closed?

**Comment by robertlevonyan** [comment]
it is not stale

**Comment by HBiSoft** [comment]
This should be fixed in the latest release - `0.1.16`

**Comment by robertlevonyan** [comment]
tnx
