### ISSUE TITLE
setAudioSource failed on screen recording

### ISSUE THREAD

**Issue by YLPeng** [HBiSoft/HBRecorder#83]
Hello, 

Thank you for developing this library:)

I have received following exception when trying to record the screen. The permission for RECORD_AUDIO has granted prior to calling the record. Could you please give me a hint?

Screen recording on error!: errorCode:100, reason:java.lang.RuntimeException: setAudioSource failed.
        at android.media.MediaRecorder.setAudioSource(Native Method)
        at com.hbisoft.hbrecorder.ScreenRecordService.initRecorder(ScreenRecordService.java:464)
        at com.hbisoft.hbrecorder.ScreenRecordService.onStartCommand(ScreenRecordService.java:224)
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4087)
        at android.app.ActivityThread.access$1800(ActivityThread.java:219)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1891)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

**Comment by YLPeng** [comment]
After double checking the record audio permission it worked.. closing. Thanks
